config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users,
              controllers: {registrations: 'registrations'}
            # path: '',
            # path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
            # controllers: {omniauth_callbacks: 'omniauth_callbacks'}
            
  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end
  
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  
  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  
  get 'search' => 'pages#search'
  
  #AirKong
  get 'dashboard' => 'dashboards#index'
  
  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end
  
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end 
  
  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"
  post '/add_card' => "users#add_card"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: "User"
    belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"
    
    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, :recipient_id
    
    scope :involving, -> (user) {
        where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
    }    
    
    scope :between, -> (user_A, user_B) {
        where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", user_A, user_B, user_B, user_A)
    }   
end

app/models/guest_review.rb
class GuestReview < Review
    belongs_to :guest, class_name: "User"
end

app/models/host_review.rb
class HostReview < Review
        belongs_to :host, class_name: "User"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  
  validates_presence_of :context, :conversatin_id, :user_id
  
  def message_time
    self.created_at.strftime("%v")
  end
  
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  enum status: {Waiting: 0, Approved: 1, Declined: 2}
  
  belongs_to :user
  belongs_to :room
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}
  
  belongs_to :user
  has_many :photos
  has_many :reservations
  
  has_many :guest_reviews
  
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  
  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end
  
  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable, :omniauthable
         
  validates :fullname, presence: true, length: {maximum: 50}
  
  has_many :rooms
  has_many :reservations
  
  has_many :guest_reviews, class_name: "GuestReview", foreign_key: "guest_id"
  has_many :host_reviews, class_name: "HostReview", foreign_key: "host_id"
  
  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.fullname = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider

        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
        "https//www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/host_reviews_helper.rb
module HostReviewsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airpikachu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
    
  </head>

  <body>
        
      <%= render 'shared/navbar' %>
      <%= render 'shared/message' %>

       <div class="container">
          <%= yield %>
       </div>
       
       
  </body>
</html>

app/views/reviews/_guest_form.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-normal" data-toggle="modal" data-target="#myModal_<%= reservation.id %>">
  Review Host
</button>

<!-- Modal -->
<div id="myModal_<%= reservation.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-left">Review Your Host</h4>
      </div>
      <div class="modal-body">
        <%= form_for current_user.guest_reviews.new do |f| %>
            <div class="form-group text-center">
              <div id="stars"></div>
            </div>
            <div class="form-group">
              <%= f.text_area :comment, rows: 3, class: "form-control" %>
            </div>

            <%= f.hidden_field :room_id, value: reservation.room.id %>
            <%= f.hidden_field :reservation_id, value: reservation.id %>
            <%= f.hidden_field :host_id, value: reservation.room.user.id %>

            <div class="text-center">
              <%= f.submit "Add Review", class: "btn btn-normal" %>
            </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  $('#stars').raty({
    path: '/assets',
    scoreName: 'guest_review[star]',
    score: 1
  });
</script>

app/views/reviews/_guest_list.html.erb
<% if @guest_reviews.count == 0 %>
    <div class="text-center">
        <h4>There are no reviews</h4>
    </div>
<% else %>

    <% @guest_reviews.order(id: :desc).each do |r| %>
        <hr/>
        <div class="row">
            <div class="col-md-3 text-center">
                <strong><%= r.guest.fullname %></strong>
            </div>
            <div class="col-md-9">
                <div id="star_<%= r.id %>"></div>
                
                <% if current_user && current_user == r.guest %>
                    <span class="pull-right">
                        <%= link_to r, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-trash-o fa-lg"></i>
                        <% end %>
                    </span>
                <% end %>
            <div><%= r.created_at.strftime("%v") %></div>
            <div><%= r.comment %></div>
            </div>

        </div>
        
        <script>
          $('#star_<%= r.id %>').raty({
            path: '/assets',
            readOnly: true,
            scoreName: 'host_review[star]',
            score: <%= r.star %>
          });
        </script>
        
    <% end %>
<% end %>

app/views/reviews/_host_form.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-normal" data-toggle="modal" data-target="#myModal_<%= reservation.id %>">
  Review Guest
</button>

<!-- Modal -->
<div id="myModal_<%= reservation.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-left">Review Your Guest</h4>
      </div>
      <div class="modal-body">
        <%= form_for current_user.host_reviews.new do |f| %>
            <div class="form-group text-center">
              <div id="stars"></div>
            </div>
            <div class="form-group">
              <%= f.text_area :comment, rows: 3, class: "form-control" %>
            </div>

            <%= f.hidden_field :room_id, value: reservation.room.id %>
            <%= f.hidden_field :reservation_id, value: reservation.id %>
            <%= f.hidden_field :guest_id, value: reservation.user.id %>

            <div class="text-center">
              <%= f.submit "Add Review", class: "btn btn-normal" %>
            </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  $('#stars').raty({
    path: '/assets',
    scoreName: 'host_review[star]',
    score: 1
  });
</script>

app/views/reviews/_host_list.html.erb
<% if @host_reviews.count == 0 %>
    <div class="text-center">
        <h4>There are no reviews</h4>
    </div>
<% else %>

    <% @host_reviews.order(id: :desc).each do |r| %>
        <hr/>
        <div class="row">
            <div class="col-md-3 text-center">
                <strong><%= r.host.fullname %></strong>
            </div>
            <div class="col-md-9">
                <div id="star_<%= ri.id %>"></div>
                
                <% if current_user && current_user == r.host %>
                    <span class="pull-right">
                        <%= link_to r, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-trash-o fa-lg"></i>
                        <% end %>
                    </span>
                <% end %>
                <div><%= r.created_at.strftime("%v") %></div>
                <div><%= r.comment %></div>
            </div>
        </div>
        
        <script>
          $('#star_<%= r.id %>').raty({
            path: '/assets',
            readOnly: true,
            scoreName: 'host_review[star]',
            score: <%= r.star %>
          });
        </script>
        
    <% end %>
<% end %>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |value| %>
            toastr.error('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |key, value| %>
            <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
            toastr['<%= type %>']('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" style ="margin-bottom: 0px">
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to "AirPikachu", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <button class="btn btn-form btn-small">
                    <%= link_to "Become a host", new_room_path , style: "color: white; text-decoration: none;" %>
                </button>
            </li>
            <% if (!user_signed_in?) %>
                <li><%= link_to "Login", new_user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <!--<%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;-->
                  <%= current_user.fullname %><span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Dashboard", dashboard_path %></li>
                <li><%= link_to "Manage Listing", rooms_path %></li>
                <li><%= link_to "List Your space", new_room_path %></li>
                <li><%= link_to "Your Reservations", your_reservations_path %></li>
                <li><%= link_to "Your Trips", your_trips_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>            
            <% end %>
         </ul>
    </div><!--/.nav-collapse -->
</div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/rooms/#{params[:id]}") %>

<nav class="navbar navbar-default" style="background-color: #565A5C">
    <div class="container">
        <ul class="nav navbar-nav">
            <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "Dashboard", dashboard_path %></li>
            <li <% if current_page?(rooms_path) %> class="active" <% end %> ><%= link_to "Manage Listings", rooms_path %></li>
            <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "Messages", conversations_path %></li>
             <li <% if current_page?(payment_method_path) %> class="active" <% end %> ><%= link_to "Account Settings", payment_method_path %></li>
        </ul>
    </div>
</nav>

<% end %>